"""Treasury cash operations in the aggregate, par-valued debt model.

Redemptions are financial transactions, not household income or public spending.
The fiscal dividend is an explicit, cash-funded transfer decided before consumption.
"""
import numpy as np

def purchase_public_bonds(e, budget):
    """BC buys outstanding bonds at par, bank first, then households.

    Execute bounded quantities and book the quantities actually sold. At a
    full liquidation, copying each claim before subtracting it avoids the
    negative residuals generated by ``total * (claim / total)``. No tolerance
    is used to forgive a negative position or to create a balancing transfer.
    Reserves are reconciled by the caller with the other weekly operations.
    """
    claims=np.asarray(e.Bh,dtype=float)
    if (not np.isfinite(budget) or budget<0 or not np.isfinite(claims).all()
            or np.any(claims<0) or not np.isfinite(e.B_bank) or e.B_bank<0):
        raise ValueError('Achat de titres publics invalide')
    bank=min(float(budget),e.B_bank)
    available=float(claims.sum());want=min(max(budget-bank,0.),available)
    if want==available:
        household=claims.copy()
    elif want>0:
        household=np.minimum(claims,want*(claims/available))
    else:
        household=np.zeros_like(claims)
    total=float(bank+household.sum())
    if total>0:
        e.cbar_cb=(e.cbar_cb*e.B_cb+e.i_B*total)/(e.B_cb+total)
        e.B_bank-=bank;e.Bh-=household;e.B_cb+=total
        for h,value in enumerate(household):e.led.dep[f'H{h}']+=value
    return dict(bank=float(bank),households=household,total=total)

def redeemable_debt(e):
    """Conversion advances AG_free remain outside ordinary debt repayment."""
    return float(e.B_bank+e.B_cb+e.Bh.sum()+max(e.AG-e.AG_free,0.))

def rebate_plan(e,annual_gdp,cash_available=None):
    p=e.p
    reserve=p.gov_cash_ratio*annual_gdp
    cash=e.led.dep['G'] if cash_available is None else min(e.led.dep['G'],cash_available)
    excess=max(cash-reserve,0.)
    if p.treasury_redeem_all:
        excess=max(excess-redeemable_debt(e),0.)
    limits=[excess*(-np.expm1(-p.treasury_rebate_speed/52)),p.treasury_rebate_cap*annual_gdp/52]
    if p.treasury_drawdown_cap is not None:
        previous=e.flow_history[-1] if e.flow_history else {}
        # Remove the previous dividend from the measured deficit to recover
        # the preceding week's pre-dividend fiscal surplus. Financial principal
        # transactions are already excluded by the fiscal accounting identity.
        surplus=max(previous.get('treasury_dividend',0.)-previous.get('deficit',0.),0.)
        limits.append(surplus+p.treasury_drawdown_cap*annual_gdp/52)
    amount=min(limits)
    # Equal payment per person. This is a fiscal dividend, not a tax refund.
    return amount*p.N/p.N.sum()

def redeem_public_debt(e,budget):
    """Proportional redemptions at book/par value with a funded cash budget.

    All creditor positions must be represented in the model. No FX creditor is
    invented; current worldn only holds public bonds domestically.
    Bank reserves are reconciled by the caller at the end of the weekly ledger.
    """
    if not np.isfinite(budget) or budget<0:raise ValueError('Budget de remboursement invalide')
    if not np.isfinite([e.AG,e.AG_free]).all() or e.AG_free<0 or e.AG<e.AG_free:
        raise ValueError('Avances publiques invalides')
    if abs(e.B_foreign)>1e-9:raise NotImplementedError('Remboursement souverain à des créanciers étrangers non représentés')
    claims=np.r_[e.Bh,e.B_bank,e.B_cb,max(e.AG-e.AG_free,0.)].astype(float)
    if not np.isfinite(claims).all() or np.any(claims<0):raise ValueError('Créances publiques invalides')
    amount=min(budget,max(e.led.dep['G'],0.),float(claims.sum()))
    allocations=(claims.copy() if amount==claims.sum() else
        np.minimum(claims,claims*(amount/claims.sum()))) if claims.sum()>0 else np.zeros_like(claims)
    household=np.array([e.led.transfer('G',f'H{h}',allocations[h]) for h in range(3)])
    e.Bh-=household
    bank,central,advances=allocations[3:]
    e.led.dep['G']-=bank+central+advances
    e.B_bank-=bank;e.B_cb-=central;e.AG=e.AG_free+(max(e.AG-e.AG_free,0.)-advances)
    e.B=float(e.Bh.sum()+e.B_bank+e.B_cb)
    return dict(households=float(household.sum()),bank=float(bank),central_bank=float(central),
                advances=float(advances),total=float(household.sum()+bank+central+advances))
